### ISSUE TITLE
Makefile not working 

### ISSUE THREAD

**Issue by windows31** [amalon/hoganfam-trains#1]
Hey so it seems the makefile provided doesn't seem to work (I'm on windows) and neither do the files located in the srv folder do as they don't show up as trains on the server with your resource pack.

**Comment by amalon** [comment]
I'll happily look at pull requests to improve compatibility with other OSes. Other than that the best I can do is probably to make a release and upload the output files. I'll do this for you when I get the opportunity over the next few days.

**Comment by windows31** [comment]
Alright, if you could do that that would be much appreciated!.

**Comment by amalon** [comment]
Can you try the files released here:
https://github.com/amalon/hoganfam-trains/releases/tag/v23.02.a

Do say if you encounter any other issues with it.

I'll close this issue as wontfix for now, since building on Windows isn't something I'm personally going to work on.
