### ISSUE TITLE
Train not turning

### ISSUE THREAD

**Issue by windows31** [amalon/hoganfam-trains#2]
Hey there, So when using your trains it seems like they dont follow rails? i have a turn which it didnt turn accordingly but rather crashed into the block infront of it as there was a wall.. how would one make the train move according to rails beneath it?

**Comment by amalon** [comment]
Its unclear from your description what is wrong. I've given it a try with rails (I normally use tccoasters), and it mostly behaves as I'd expect, though it happily continues off the end of the rails if I do nothing to prevent it. The way I make the trains does result in some carriages flipped, which can hit corner cases in traincarts, but it mostly works in my experience.

Perhaps you can share a screenshot of the rail and what happens to it.
It may also be helpful to edit the train by pointing at it and doing `/train edit`, then doing `/train status` to see what its doing.
Also are you on the latest traincarts version?

**Comment by windows31** [comment]
Yes im on the latest and what i mean is it is not turning at turns of the rail track.. it is trying to just move forward.
i need the train to turn according to the rail tracks

**Comment by windows31** [comment]
And also i'd like to know is there a way to prevent players from walking out of the trains front and back? I dont care about the sides but just about the front and back.

**Comment by amalon** [comment]
yeh, turning works fine for me with both tccoasters, and when i tried with normal rail (with both 45 degree and 90 degree turns). If /train status doesn't report it as derailed and its still doing it, it sounds like it could be a traincarts issue.

The floor of the train is done using platforms (invisible shulkers). I could put a couple at the ends of the trains so you can't as easily walk out the ends.

**Comment by windows31** [comment]
well uh it doesnt work for me how come then? could you like join my server and check it?

**Comment by windows31** [comment]
Could you show me a screenshot of how your rails are setup?

**Comment by amalon** [comment]
Here's one example with rails that seems to work fine as long as there's enough length for the train (there's a station sign under it):
![2023-02-16_18 42 40](https://user-images.githubusercontent.com/210303/219458833-bc576e98-ae6f-4fe9-9863-e61fa6b6df5b.png)
![2023-02-16_18 42 47](https://user-images.githubusercontent.com/210303/219458909-f733f4e3-6a3b-40e5-8dd9-d8c64e49d64d.png)

**Comment by windows31** [comment]
My tracks are not like that. They are like a sudden turn not a gradual turn in your case like a sudden 90 degree turn so idk if that is why
I can send the screenshot when I'm on my pc

**Comment by amalon** [comment]
right angle turns work here (though it looks rather ugly):
![2023-02-17_13 15 20](https://user-images.githubusercontent.com/210303/219662777-d39b6934-6b9f-40f5-9700-7273f78033e5.png)
![2023-02-17_13 15 14](https://user-images.githubusercontent.com/210303/219662801-d64e0a45-fbc7-4c65-bd1a-4712fac64c30.png)

This isn't really close to where the train is spawned is it? in my experience they need plenty of space at spawn or they do get messed up.

**Comment by windows31** [comment]
I can show you a screenshot of the curve

**Comment by windows31** [comment]
Hey I've seen to have fixed the issue by somehow re installing the plugin so thanks for the help
