### ISSUE TITLE
File path exceeding

### ISSUE THREAD

**Issue by windows31** [amalon/hoganfam-trains#3]
Hey, Its just that in the resource pack some files are located deep inside the pack and have a long file name thus making the pack not work when i convert it to bedrock as there is a 80 char file limit on the file paths. im just wondering if i could get a version of the resource pack which has less folders to get to the files along with short file names so the bedrock pack can work in the future. :)

**Comment by windows31** [comment]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/77492020/230780961-75b0094d-e92d-4a7f-9193-7586dce716e3.png">

**Comment by amalon** [comment]
Thanks. Yeh should be easy enough to avoid given the files have pretty long names already. I'll try and do this in the next few days, along with another release while I'm at it.

**Comment by amalon** [comment]
Is it just the json files, or do the png textures end up extra long too?

**Comment by amalon** [comment]
Hopefully the new release has sorted it for you. If not please let me know.
Thanks
