### ISSUE TITLE
Update to 1.19.4 (or, even better, to 1.20)

### ISSUE THREAD

**Issue by Milk-Cool** [amalon/hoganfam-trains#4]
Hello!
I was wondering if you are willing to update this project and update the pack to the latest versions of minecraft, those being 1.19.4 and 1.20.1. I am willing to use this pack on my own server which runs paper 1.19.4, but unfortunately, the resource pack does not work on this version as intended -- i only see three diffeerent minecarts.
So, will you update this project?

**Comment by amalon** [comment]
As described in the README.md, you need the traincarts plugin, and you spawn trains in the normal traincarts way rather than by placing minecarts.

**Comment by Milk-Cool** [comment]
No, I installed the traincarts plugin and I am doing everything according to instructions.
Here's aa video demonstrating the issue: https://files.catbox.moe/whjg58.mp4

**Comment by amalon** [comment]
My apologies. Did this work prior to 1.19.4? Regardless of the resource pack it doesn't look like a metro train, which looks more like this without the resource pack:
![2023-06-29_07 50 12](https://github.com/amalon/hoganfam-trains/assets/210303/2a7bd21c-1456-41e3-9777-7f70e444b37a)

That suggests that its not loading from the saved train model correctly.
* Is it possible there is another saved train called metro in your SavedTrainProperties.yml or savedTrainModules/?
* Does spawning a class158 behave any differently?

**Comment by Milk-Cool** [comment]
Spawning a class158 just spawns a different set of minecarts, and there aren't any other trains installed. However, it's worth mentioning (I just noticed) that hoganfam_trains.yml is actually named hoganfam_trains.yml.in, which might be the cause of all the problems. I'll check when I get home

**Comment by amalon** [comment]
Ah i see. The *.yml.in files are the source files that are used for building hoganfam_trains.yml (they get combined together to avoid duplication in the files I need to edit). You can find built yml files in [releases](https://github.com/amalon/hoganfam-trains/releases).
It won't be able to read the .yml.in file, so then it can't find the saved train, so the [spawn sign](https://wiki.traincarts.net/p/TrainCarts/Signs/Spawner#Third_and_fourth_lines) will read "metro", interpret the m as a regular minecart, t as tnt minecart, and i'm guessing one of the other letters as something else.

**Comment by amalon** [comment]
I'll try and improve the README to make it clearer, and add the download links.

**Comment by Milk-Cool** [comment]
alright, thanks for the info!

**Comment by Milk-Cool** [comment]
It worked! tysm!
