### ISSUE TITLE
How can I support you?

### ISSUE THREAD

**Issue by Pro245Mc** [amalon/hoganfam-trains#6]
Hi james,

Sorry for writing this here, I'm not sure where i can contact you. Maybe you can show me.

I'm a fan of your train resoures pack, and have been waiting a while for the underground train "outside shell" to be finished. I was wondering if i could donate to you and have at least the outside finished? I'm excited to see you working on a new train too. where can i get it? Is it possible to have the pack updated to 1.20.1? 

I don't really know how to use the "make" file. But is there a way I can test the new train?

**Comment by amalon** [comment]
Hi. Here is fine, as is the [Matrix Chat Room](https://matrix.to/#/#mc-trains:hoganfam.uk?via=hoganfam.uk).

When you say the underground train, do you mean the one called [metro](https://github.com/amalon/hoganfam-trains/blob/master/docs/metro.md)? That one is intended to be fairly simple and plain. What changes were you wanting?

I'm open to receiving donations to show appreciation & help motivate, though probably not for specific work at the moment. Feel free to request features though.

The LNER A4 (Mallard) is still a work in progress, though I'll look into getting CI working so you can download development versions easily. The existing resource packs should work fine on 1.20.1 though.

**Comment by Pro245Mc** [comment]
hi there, yes in understand. oh, ok. I thought the outside on the metro would have an updated design, but i looks great the way it is. (although the inside isnt finished i think?) Do you have a link for donations?

**Comment by amalon** [comment]
I don't have a link for donations just yet, but thanks anyway!

**Comment by Pro245Mc** [comment]
no problem, let me know when you have one. 
I have a cool feature that could make it more realistic.
Having the "minecart sounds" play when the train is moving.  :)

**Comment by amalon** [comment]
> I don't really know how to use the "make" file. But is there a way I can test the new train?

FYI the ![LNER Class A4 (Mallard)](https://github.com/amalon/hoganfam-trains/blob/master/docs/a4.md) is now included in the [v23.09.a release](https://github.com/amalon/hoganfam-trains/releases/tag/v23.09.a).
